#!/bin/sh

# Update system
sudo pacman -Syu

# Pacman
sudo pacman -S \
    zsh \
    neovim \
    stow \
    starship \
    keepassxc \
    alacritty \
    exa \
    bat \
    tmux \
    ranger \
    spotify-launcher \
    php apache php-apache \
    qbittorrent \
    zoxide \
    trash-cli \
    go \
    github-cli \
    kdocker \
    thunderbird \
    inkscape \
    gimp \
    paru

# Switch to zsh
chsh -s $(which zsh)

# Dotfiles
git clone https://github.com/darccyy/dotfiles ~/dotfiles
cd ~/dotfiles
stow */

# Scripts
git clone https://github.com/darccyy/scripts ~/scripts

# Tmux tpm
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# Yay
paru -S \
    librewolf-bin

# Rust with rustup
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

# Install with cargo
cargo install \
    just \
    cargo-watch

# Windscribe
# https://windscribe.com/install/desktop/linux_zst_x64

# Fira code nerd font
sudo pacman -S ttf-firacode-nerd

